//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika2011.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zayavka
    {
        public int id { get; set; }
        public string adress { get; set; }
        public Nullable<int> komnatyCount { get; set; }
        public Nullable<int> ploshad { get; set; }
        public Nullable<int> idStatus { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual status status { get; set; }
        public virtual users users { get; set; }
    }
}
